# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      # basic circleci jdk 1.8 container + openshift CLI
      - image: mk83ko/toolscontainer:circleci-openshift
      
    working_directory: ~/repo
    
    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m
    
    steps:
      - checkout
      
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "pom.xml" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
          
      - run: mvn dependency:go-offline
      
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
        
      # run build
      - run: mvn package
      
      - run: 
        name: deploy to openshift
        command: |
          mkdir -p /tmp/upload/deployments
          pwd 
          oc login https://api.starter-us-west-1.openshift.com:443 --username=$OPENSHIFT_USER --password=$OPENSHIFT_PASSWORD \;
          
      - run:
          name: save test results 
          command: |
            mkdir -p ~/junit/ 
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/junit/ \;
          when: always
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/junit 